export {
  at,
  cameraShake,
  hitStop,
  marker,
  play,
  stop,
  timeline,
  type CameraShakeAction,
  type HitStopAction,
  type MarkerAction,
  type PlayAction,
  type StopAction,
  type TimelineAction,
  type TimelineDefinition,
  type TimelineEntry,
} from '@nachi/core';
export {
  defineEffect,
  fxMaterial,
  lowerCurve,
  meshFxElement,
  type MeshFxElement,
  type TimelineAuthoringElement,
  type TimelineAuthoringElements,
  type TimelineEffectConfig,
  type TimelineEffectDefinition,
  type TimelineFxDissolveConfig,
  type TimelineFxMaterialConfig,
  type TimelineOverLifeInput,
} from './authoring.js';
export {
  VFXSystem,
  type CameraShakeSample,
  type CameraShakeTarget,
  type TimelineActionEvent,
  type TimelineElementState,
  type TimelineEffectInstance,
  type TimelineEffectSpawnOptions,
  type TimelineSystemOptions,
} from './runtime.js';
