export {
  cone,
  createConeGeometry,
  createCylinderGeometry,
  createMagicCircleGeometry,
  createRingGeometry,
  createSlashArcGeometry,
  cylinder,
  magicCircle,
  ring,
  slashArc,
  type ConeOptions,
  type CylinderOptions,
  type MagicCircleOptions,
  type MeshFxElementMetadata,
  type MeshFxMesh,
  type RingOptions,
  type SlashArcOptions,
} from './geometry.js';
export {
  fxMaterial,
  polarUV,
  uvFlow,
  type CartesianUvFlowAuthoring,
  type FxBlending,
  type FxDissolveConfig,
  type FxFresnelConfig,
  type FxMaterialConfig,
  type FxMaterialControls,
  type FxNodeMaterial,
  type OverLifeCurve,
  type OverLifeInput,
  type PolarUvAuthoring,
  type PolarUvAuthoringConfig,
  type UvFlowAuthoringConfig,
} from './material.js';
export { MeshFxDiagnosticError, type MeshFxDiagnostic } from './diagnostics.js';
export {
  applyVat,
  resolveVatFrames,
  type VatAxisMap,
  type VatConfig,
  type VatControls,
  type VatFrameOrder,
  type VatFrameSample,
  type VatInterpolation,
  type VatMesh,
  type VatNormalEncoding,
  type VatPositionEncoding,
  type VatPositionMode,
  type VatRemapRange,
  type VatVertexLookup,
} from './vat.js';
